### ISSUE TITLE
Differences in total of >= 5kb loops

### ISSUE THREAD

**Issue by caleblareau** [aryeelab/dnaloop#10]
Some variation in the number of loops we report with >= 5kb 

In `qc-report.R`--
awkcmd <- paste("awk '$1 == $4 {print $5-$3 \" \" $8}' " , sfilename, sep = "")
#other R commands to bin/format

naive_esc_1 naive_esc_2 primed_esc_1 primed_esc_2
26448       33328        32680        39331

In `preprocess_chiapet_fastq.sh`--
DIFF_ANCHOR_PETS_5KB=`awk '($1==$4) && ($5-$3 >= 5000)' anchor_interactions.tmp | wc -l`
naive_esc_1 naive_esc_2 primed_esc_1 primed_esc_2
20221       26699        23361        32077

Example from the `esc_010` data

**Comment by martinaryee** [comment]
Is the R awkcmd subsetting to >=5kb?

**Comment by caleblareau** [comment]
Eventually. I'm creating bins though with variable loop widths

vals <- c(-Inf, 0, 1000, 2000, 3000, 4000, 5000, Inf)
  sapply(seq(1, length(vals)-1), function(i){
    with(df, sum(df[dist >= vals[i] & dist < vals[i+1], "counts"]))

**Comment by caleblareau** [comment]
As discussed on 21 April, variation comes from comparing a single sample to when the samples are all together. Martin's new QC report format reflects this. We may tweak the appearance (e.g. a more hidden log file) for user simplicity.
